### ISSUE TITLE
App Idea: Bulk Pregen Generation

### ISSUE THREAD

**Issue by adeets-22** [getpara/awesome-para#5]
Description: 
Build an app with bulk pregen generation, showcasing how to take a list of identifiers, create [pregenerated wallets](https://docs.usecapsule.com/integration-guides/wallet-pregeneration), and store them securely in a database. 

Use Case: 
For example, the app could pregenerate wallets for all your Twitter followers, enabling them to claim their wallets and receive rewards or assets to these wallets. This tool can streamline engagement campaigns and can be valuable to brands, creators, etc

**Comment by fraolb** [comment]
Hello @adeets-22, Can I get assigned to this task?

**Comment by developerfred** [comment]
@adeets-22 Is this activity still available?

**Comment by adeets-22** [comment]
Hello @developerfred! This is being worked on by someone else, but we're planning to do another round of bounties soon :)

**Comment by adeets-22** [comment]
hey @fraolb are you still working on this?

**Comment by fraolb** [comment]
Hello @adeets-22, yes I am working on it. I will be pushing a PR soon.

**Comment by Micholn** [comment]
> Hello [@developerfred](https://github.com/developerfred)! This is being worked on by someone else, but we're planning to do another round of bounties soon :)

I'll be looking forward to the other round of bounties, thank you.

**Comment by jlm0** [comment]
@fraolb Can you update on the status of this submission as well? Are you still working on both projects? https://github.com/getpara/awesome-para/issues/12

**Comment by pbkompasz** [comment]
@jlm0 If the task becomes available, I would take it up. My idea is to create a "Twitter Giveaway" platform, which would include an admin dashboard where a user can log in with their Twitter account, pull their followers, generate wallets for them, and mint a giveaway NFT for each follower. On a separate page, users would be able to claim their wallets and manage the received funds.

**Comment by pbkompasz** [comment]
@jlm0 If the task becomes available, I would take it up. My idea is to create a similar giveaway app for a social media platforms that has an API through which I can pull a users followers. The app would include an admin dashboard where a user can link their social media account, pull their follower list w/ an API call, generate the wallets and distribute giveaway NFTs. On a separate page, users would be able to claim their wallets and manage the received NFT.

**Comment by adeets-22** [comment]
@pbkompasz happy to assign this to you - we haven't heard from the previous assignee in a few weeks. Would love if you can work on this idea!

**Comment by fraolb** [comment]
Hello @adeets-22 , actually I am working on the project. The code base is [here](https://github.com/fraolb/para_example_pregenerated_wallets). The documentation of the code is not up to date. for example to create a wallet [createWalletPreGen](https://docs.getpara.com/integration-guides/wallet-pregeneration) but the updated package is createPregenWallet. 
I am building for Twitter accounts to create a pregen wallet for their followers. 

`
const handlePregenWallet = async (userIdentifier: string) => {
    console.log("the userIdentifier is ", userIdentifier);
    try {
      const hasWallet = await para.hasPregenWallet({
        pregenIdentifier: userIdentifier,
        pregenIdentifierType: OAuthMethod.TWITTER,
      });
      console.log("user wallet ", hasWallet);
      if (!hasWallet) {
        const pregenWallet = await para.createPregenWallet({
          type: WalletType.EVM,
          pregenIdentifier: userIdentifier,
          pregenIdentifierType: OAuthMethod.TWITTER,
        });
        console.log("New pregenerated wallet created:", pregenWallet.id);
        return pregenWallet.id;
      } else {
        console.log("Pregenerated wallet already exists for this user");
        return null;
      }
    } catch (error) {
      console.error("Error handling pregenerated wallet:", error);
      return null;
    }
  };
`

The issue I am facing is on _createPregenWallet_ , it returns an error message of 
`Error handling pregenerated wallet: Error: timed out waiting for wallet address
    at Para.eval (ParaCore.js:1910:19)
    at Generator.next (<anonymous>)
    at fulfilled (ParaCore.js:28:58)`

The documentation do not contain broader description so I was going through the npm package.

**Comment by pbkompasz** [comment]
@adeets-22 Does this change anything, or am I assigned?

**Comment by adeets-22** [comment]
you're assigned! @pbkompasz

**Comment by adeets-22** [comment]
hey @pbkompasz! any update here?

**Comment by pbkompasz** [comment]
@adeets-22 It's almost done! I went with Warpcast as the social media platform (since only the enterprise Twitter API allows for retrieving followers). I'll open a PR tomorrow. Here's the [repo](https://github.com/pbkompasz/invite-pregen-wallet) with the implementation. There's still some work I haven't pushed yet, and I need to clean up the frontend a bit.

**Comment by adeets-22** [comment]
Great - that sounds good!

**Comment by pbkompasz** [comment]
Hi @adeets-22 , my PR that closes the issue has been merged. How can I claim the bounty?

**Comment by adeets-22** [comment]
Hi @pbkompasz great news! What is your Telegram handle, I'll ping you there and we'll close out your payment.

**Comment by adeets-22** [comment]
Also may have another project for you if your bandwidth is free atm!

**Comment by pbkompasz** [comment]
My Telegram is @pbkompasz, and I’d be happy to take on another project.

**Comment by adeets-22** [comment]
Just pinged you on tg
